#!/usr/bin/env bash

hook_dir="$(dirname "${BASH_SOURCE[0]}")"
scripts_dir="${hook_dir}/scripts"

function run_clang_format_diff() {
    echo "Running clang-format-diff..."

    fmt_diff=$(git diff --no-ext-diff -U0 --no-color --relative --cached | ${scripts_dir}/clang-format-diff.py -p1)

    colorize_diff='
        /^+/ { printf "\033[1;32m" }
        /^-/ { printf "\033[1;31m" }
        // { print $0 "\033[0m"; }'

    if [ -n "${fmt_diff}" ]; then
        echo "${fmt_diff}" | awk "${colorize_diff}"
        echo -e "\nPlease re-format above files before commit"
        exit 1
    fi

    echo "clang-format-diff passed"
}

function run_cpplint_check() {
    echo "Running cpplint check..."

    changed_files=$(git diff --cached --name-only | grep -iE '\.(cpp|cc|c|hpp|hh|h)$')
    if [ -n "${changed_files}" ]; then
        ${scripts_dir}/cpplint.py --quiet ${changed_files}
        if [ "$?" -ne 0 ]; then
            exit 1
        fi
    fi

    echo "cpplint check passed"
}

run_clang_format_diff && \
run_cpplint_check
